name: Setup Python Env
description: Install project dependencies
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
      shell: bash
      
 